### PR TITLE
Doc: Install: make PS snippet just working w/o proper execution policies

### PR DESCRIPTION
**Pull request by Al2Klimov**
As a user I'd like to just copy and paste that snippet into admin PS on a fresh Windows.

### CODE REVIEW

**Comment by julianbrost** [comment]
I just did something similar and it looks like you have to change this system-wide for things to function properly. So in my example, I did `Set-ExecutionPolicy -Scope Process` which then resulted in the daemon not starting properly (restarted every 2 seconds).

**Comment by Al2Klimov** [comment]
Sure. But this PR is for lazy C&Pers who just want an Icinga 2 on the box (like me).

**Comment by julianbrost** [comment]
It's a multi-line script block already. Would there be harm in just adding the minimal `Set-ExecutionPolicy` that's needed for everything to work?

**Comment by Al2Klimov** [comment]
Only if it may mismatch with what the end user wants.

**Comment by LordHepipud** [comment]
Thank you for the PR and the input. Honestly I do not want this change inside the script. There is a reason, why the execution policy check is at the beginning of the script. As Julian mentioned, there will be more trouble later on when the execution policies are not set properly, which will result in negative user feedback why feature x, y, z is not working.

Setting up execution policies once or even during the own automation deployment process, isn't that complicated and results in better overall user experience.

**Comment by julianbrost** [comment]
I didn't find anything in the docs that made a clear statement what execution policy is required, https://icinga.com/docs/icinga-for-windows/latest/doc/110-Installation/01-Getting-Started/#requirements just links a generic documentation page in that regard. I tried to figure out what is needed, guessed `-Scope Process` should be enough but I was wrong and the service failed to start. So I think there's room for improvement here.

**Comment by Al2Klimov** [comment]
And that improvement IMAO should be a line on top of the script I touch here which sets the desired execution policy.

**Comment by LordHepipud** [comment]
There are many different ways to properly run PowerShell code in your environment. Allow everything, allow signed code only, or simply flag code as "whitelisted".
Linking a generic documentation is one idea, but as Windows user you should know and get back to your security team, on how to run PowerShell code.

I will not add a one-liner to a pre-written script for installing PowerShell code from the internet. I will not take responsibility for possible security risks or by randomly configuring a Windows environment, because someone does not get back to their internal security or check on how to configure security.

I'm sorry, but I'm not going to do that.

**Comment by julianbrost** [comment]
To me (but I'm also not a PowerShell expert), the documentation is not clear on the requirements in respect to the execution policy. I tried to set the minimum I considered to be necessary which was `Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass` because I assumed that I have to set the policy because I just downloaded something from the internet and want to run it in the current session. I didn't expect that I have the system configuration to actually allow running software I just installed.

**Comment by LordHepipud** [comment]
As Julian mentioned. we have the [Getting Started](https://icinga.com/docs/icinga-for-windows/latest/doc/110-Installation/01-Getting-Started/), which says under **Requirements**

* [Execution Policies](https://docs.microsoft.com/de-de/powershell/module/microsoft.powershell.core/about/about_execution_policies) allowing module/script execution

With a link to the Microsoft documentation on what type of Execution-Policies are available and how they work.

If we need to state things clearer, I'm fine with that. I just don't want to copy the entire Microsoft Docs for this.

The docs part is very detailed on each different setting, on how you configure them and how they affect either your system or PowerShell environment.

Am I missing something here?

**Comment by julianbrost** [comment]
I'm missing something like this in the documentation (might not be accurate, I'm guessing here, that's why I would like this to be documented):

The PowerShell execution policy must be set up so that it allows:
- execution of the `IcingaForWindows.ps1` installation script downloaded in the installation guide
- any user that will use the Icinga Management Console to execute files in `C:\Program Files\WindowsPowerShell\Modules`
- for the Icinga PowerShell Service: the user that will run it (by default: ...) to execute files in `C:\Program Files\WindowsPowerShell\Modules`
- for PowerShell check commands executed from Icinga 2: the user that will run the Icinga 2 service (by default: Network Service (or how exactly that user is called)) to execute files in `C:\Program Files\WindowsPowerShell\Modules`

**Pull request closed without merging**
