### PR TITLE
Fix the creation of powershell arrays in Icinga2 configuration

### PR DESCRIPTION
**Pull request by RincewindsHat**

### CODE REVIEW

**Comment by LordHepipud** [comment]
Thank you for the PR. Which problem does it exactly solve?
The current implementation creates comma separated entries for PowerShell arrays. Why wrap it specifically inside `@()`?

**Comment by RincewindsHat** [comment]
When using the powershell-connector to circumvent the performance problems, comma separated values are not interpreted as an array and some calls to check functions will therefore not work as expected. Using the `@()` syntax so declare an array negates this problem in that case, since arrays are then detected as expected and properly handed to the API as an array.
If there is another (better) way to do this, I am open to suggestions.

**Comment by LordHepipud** [comment]
Thank you for the clarification. Can you please rename the variable `foo` too `psarr` and update the changelog for `v.1.10.0` with the following `Enhancement`:

```
* [#534](https://github.com/Icinga/icinga-powershell-framework/pull/534) Improves Icinga and Director configuration generator, by wrapping PowerShell arrays inside `@()` instead of simply writing them comma separated
```

Please also update the description of this PR accordingly and squash both commits to one commit only.

Thank you in advance!

**Comment by LordHepipud** [comment]
Before I forget it: Please also add a `;` behind `return "@(" + psarr + ")`

**Pull request merged**
