### PR TITLE
Get-IcingaCheckCommandConfig: move -C from every single command to template

### LINKED ISSUE #627: Director basket: consider centralising -C via command name CV
## Current Behavior

At the moment the basket defines -C (in contrast to -ExecutionPolicy, -NoLogo and -NoProfile) **on every single check command**, like this:

`try { Use-Icinga -Minimal; } catch { Write-Output 'The Icinga PowerShell Framework is either not installed on the system or not configured properly. Please check https://icinga.com/docs/windows for further details'; Write-Output 'Error:' $$($$_.Exception.Message)Components:`r`n$$( Get-Module -ListAvailable 'icinga-powershell-*' )`r`n'Module-Path:'`r`n$$($$Env:PSModulePath); exit 3; }; Exit-IcingaExecutePlugin -Command 'Invoke-IcingaCheckUsers'`

However, those strings differ only minimal:

Bildschirm­foto 2023-06-01 um 11 00 23

## Possible Solution

I suggest to make their only difference -the command name- a custom var set on every command and to centralise -C (next to -ExecutionPolicy etc.?), using the custom var. I.e.:

`try { Use-Icinga -Minimal; } catch { Write-Output 'The Icinga PowerShell Framework is either not installed on the system or not configured properly. Please check https://icinga.com/docs/windows for further details'; Write-Output 'Error:' $$($$_.Exception.Message)Components:`r`n$$( Get-Module -ListAvailable 'icinga-powershell-*' )`r`n'Module-Path:'`r`n$$($$Env:PSModulePath); exit 3; }; Exit-IcingaExecutePlugin -Command '$YourPreferedNameForCommandName$'`

## Context

https://github.com/Icinga/icinga2/pull/9062#issuecomment-1571634108

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #627

## TODO

* [x] #629 (higher prio, will merge-conflict)
* [x] #633 (higher prio, will merge-conflict)
* [x] #630 (our functional dependency)
* [x] rebase @Al2Klimov
* [x] global var for dup. string @Al2Klimov
* [x] test @Al2Klimov

### CODE REVIEW

**Comment by Al2Klimov** [comment]
@LordHepipud Before testing: does the code change look good?

**Comment by LordHepipud** [comment]
Looks good so far. We should test both, Director baskets and plain Icinga conf to ensure there is no bug remaining.
But the change looks promising

**Comment by Al2Klimov** [comment]
Plain config looks promising as well:

```
object CheckCommand "PowerShell Base" {
    import "plugin-check-command"
    command = [
        "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
    ]
    timeout = 3m
    arguments += {
        "-C" = {
            order = 0
            value = "try { Use-Icinga -Minimal; } catch { Write-Output 'The Icinga PowerShell Framework is either not installed on the system or not configured properly. Please check https://icinga.com/docs/windows for further details'; Write-Output 'Error:' $$($$_.Exception.Message)Components:`r`n$$( Get-Module -ListAvailable 'icinga-powershell-*' )`r`n'Module-Path:'`r`n$$($$Env:PSModulePath); exit 3; }; Exit-IcingaExecutePlugin -Command '$ifw_api_command$' "
        }
        "-ExecutionPolicy" = {
            order = -1
            value = "$IcingaPowerShellBase_String_ExecutionPolicy$"
        }
...
```

**Comment by Al2Klimov** [comment]
Please consider for https://github.com/Icinga/icinga-powershell-framework/milestone/28
, thanks.

**Comment by Al2Klimov** [comment]
Rebased, added change log.

**Comment by LordHepipud** [comment]
Thanks!

**Pull request merged**
