### PR TITLE
Fix backslashes in the url path causes an error

### LINKED ISSUE #186: Problem with "/" and "\" in Windows Paths
Hi
While Running "icinga> $ServiceData = Get-IcingaFrameworkServiceBinary" there pops up the following line: 
"Please enter the full path to your service binary repository:" and when I enter the path 
"C:\User\Administrator\Desktop\icinga-service-v1.0.0.zip" it doesn't work.

I expect it to work with forward and backward slashes e.g. "C:\User\Administrator\Desktop\icinga-service-v1.0.0.zip" and "C:/Users/Administrator/Desktop/icinga-service-v1.0.0.zip" 

When you enter the path with backward slashes it won't work and output an error.

### PR DESCRIPTION
**Pull request by Yonas-net**
resolves #186

### CODE REVIEW

**Review by LordHepipud — CHANGES_REQUESTED** [review]
Hello,

we will not do it this way. This will break the possibility to use web urls as it will enforce local paths instead of allowing local, web and network share paths.

Please use Test-Path to check if the path is a local path and use `\` for splitting and otherewise `/`

**Comment by Yonas-net** [comment]
I don't think that all local paths can be specified with backslash but also with a normal slash as @Nathaniel-Donahue described in the issue, so it would be better to just check if the url contains slash or backslash.

**Comment by LordHepipud** [comment]
It doesn't matter because the "fix" you provide will enforce a local path, because with your check testing for `$CustomBinaryUrl` will always result in `$CustomBinaryUrl = $TRUE`

It doesnt matter if you are using

```powershell
C:\users\dummy\service.zip
```

or

```powershell
https://example.com/binary.zip
```

Because you are always setting `$CustomBinaryUrl = $TRUE` by checking if `$FrameworkServiceUrl` is empty or not, you are not checking if it is a local path or a web path (both should work).

And therefor you are always enforcing this part:

```powershell
if ($CustomBinaryUrl) {
       $ZipArchive = Join-Path -Path $TmpDirectory -ChildPath ($FrameworkServiceUrl.Split('\')[-1]);
}
```

With the latest update, you check in addition for spaces in the path with

```powershell
if ($CustomBinaryUrl -and ($FrameworkServiceUrl.Contains('\'))) {
```

The proper solution would be this block:

```powershell
if (Test-Path $FrameworkServiceUrl) {
    $ZipArchive = Join-Path -Path $TmpDirectory -ChildPath ($FrameworkServiceUrl.Replace('/', '\').Split('\')[-1]);
} else {
    $ZipArchive = Join-Path -Path $TmpDirectory -ChildPath ($FrameworkServiceUrl.Split('/')[-1]);
}
```

Because it doesn't matter on how you specify the local path:

```powershell
icinga> Test-Path C:\Users\dummy\
True
icinga> Test-Path C:/Users/dummy/
True
icinga> Test-Path '\\network_fileshare\Icinga'
True
icinga> Test-Path '//network_fileshare/Icinga'
True
icinga> Test-Path 'www.icinga.com'
False
```

**Review by LordHepipud — APPROVED** [review]
LFTM

**Pull request merged**
