### PR TITLE
Fix typo in 01-JEA-Profiles.md

### PR DESCRIPTION
**Pull request by ChrLau**
Changed the word "Cmldet" to "Cmdlet"

### CODE REVIEW

**Comment by ChrLau** [comment]
@cla-bot check

**Comment by ChrLau** [comment]
@cla-bot check

**Comment by ChrLau** [comment]
CLA is signed. Form I got sent via email looks correct (no typos or the like), bot still does complain.
Contacted Icinga to have a look. :-)

**Comment by bobapple** [comment]
@cla-bot check

**Review by Al2Klimov — APPROVED** [review]

**Comment by LordHepipud** [comment]
Thanks!

**Pull request merged**
