### PR TITLE
[⚠️ Please don't merge yet! ⚠️] Don't pass -NoProfile, -NoLogo, -ExecutionPolicy and -C if $ifw_api_port$ is set

### PR DESCRIPTION
**Pull request by Al2Klimov**
As discussed in

* Icinga/icinga2#9062

## TODO

* [x] test @Al2Klimov

### CODE REVIEW

**Comment by Al2Klimov** [comment]
Walked through https://github.com/Icinga/icinga2/pull/9062#issuecomment-1533143736 again. Of course I chose the latest Icinga 2 Windows MSI mentioned in that PR. After the latter I patched the local file like here. Now, after Write-IcingaFrameworkCodeCache, Get-IcingaCheckCommandConfig output changed exactly like the PR diff. So far, so good.

**Comment by LordHepipud** [comment]
Thanks for the PR. Can you please add the following to the changelog.md for v1.11.0 under the `Enhancements` section and sqush it to one commit:

```
### Enhancements

* [#629](https://github.com/Icinga/icinga-powershell-framework/pull/629) Adds support for Icinga 2.14 direct API call to Icinga for Windows
```

**Comment by LordHepipud** [comment]
One side note: You will also have to edit the plain Icinga configuration setting at line 635 and beyond. Can you please update the PR accordingly?

**Comment by Al2Klimov** [comment]
# ⚠️ Please don't merge yet! ⚠️

We've discovered more problems this thing solely can't cope with!

Maybe this will even become unnecessary.

@LordHepipud

**Comment by Al2Klimov** [comment]
This has never actually worked, see discussion since https://github.com/Icinga/icinga2/pull/9062#issuecomment-1580869921

**Pull request closed without merging**
